version: "3"

services:
  task9-service:
    image: marinaagafonova/task9:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    deploy:
      mode: replicated
      replicas: 4